name: "CLA Assistant"
on:
  # issue_comment triggers this action on each comment on issues and pull requests
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: sign-or-recheck
        with:
          text: ${{ github.event.comment.body }}
          regex: '\s*(I have read the CLA Document and I hereby sign the CLA)|(recheckcla)\s*'
      
      - name: "CLA Assistant"
        if: ${{ steps.sign-or-recheck.outputs.match != '' || github.event_name == 'pull_request_target' }}
        # Alpha Release
        uses: cla-assistant/github-action@v2.1.1-beta
        env:
          # Generated and maintained by github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # JFrog organization secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_SIGN_TOKEN }}
        with:
          path-to-signatures: 'signed_clas.json'
          path-to-document: 'https://jfrog.com/cla/'
          remote-organization-name: 'jfrog'
          remote-repository-name: 'jfrog-signed-clas'
          # branch should not be protected
          branch: 'master'
          allowlist: bot*
